### ISSUE TITLE
Create Tag model

### ISSUE THREAD

**Issue by HardCodeMatter** [HardCodeMatter/focus-flow-api#2]
### 💬 Description
Create `Tag` model to database for storing tags and Pydantic schemas to validate input data.

### 📋 Requirements
- Model fields:
  - `id`: primary key;
  - `title`: tag name (required, non-unique);
  - `created_at`: date of created;
  - `updated_at`: date of updated.
- Pydantic schemas:
  - `TagBase`;
  - `TagCreate`;
  - `TagRead`;
  - `TagUpdate`.

### 🎯 Tasks
- [x] Created `Tag` model;
- [x] Make migration by alembic;
- [x] Created Pydantic schemas with validation `title` field.

**Comment by HardCodeMatter** [comment]
Done all tasks.
