### ISSUE TITLE
Realize CRUD and endpoints for tags

### ISSUE THREAD

**Issue by HardCodeMatter** [HardCodeMatter/focus-flow-api#3]
### 💬 Description
Implement CRUD and endpoints to work with `Tag` model: create, read, update and delete.

### 📋 Requirements
- Repository functions:
  - `create`, `get_all`, `update`, `delete`, `tag_exists_by_id`.
- Endpoints:
  - **POST** `/tags`: create tag:
    - Request body: `{"name": "Tag name"}`;
  - **GET** `/tags`: read tags:
    - Query; `/tags?page=1&limit=5`
  - **PATCH** `/tags/{id}/update`: update tag by id;
  - **DELETE** `/tags/{id}/delete`: delete tag by id.

### 🎯 Tasks
- [x] Create tag repository to manage data in database as required;
- [x] Create tag service;
- [x] Implement endpoints as required.

**Comment by HardCodeMatter** [comment]
Done all tasks.
