### ISSUE TITLE
Attach Tag model to Task model

### ISSUE THREAD

**Issue by HardCodeMatter** [HardCodeMatter/focus-flow-api#4]
### 💬 Description
Implement possible to add tags to tasks.

### 📋 Requirements
- Create relationship between tasks (`Task`) and tags (`Tag`) as `many-to-many`;
- Each task can have multiple tags.

### 🎯 Tasks
- [x] Create `task_tags` table to relationship between tasks and tags;
- [x] Update `Task` model to support relationship with `Tag` model;
- [x] Update `Task` API to add tags for tasks:
  - [x] Add `tags` as list as ID's in request body for creating or updating `Task` model.
  - Example: `{"title": "Some task", "tags": [1, 2, 3]}`.
