### ISSUE TITLE
Implement task filtering by tags

### ISSUE THREAD

**Issue by HardCodeMatter** [HardCodeMatter/focus-flow-api#5]
### 💬 Description
API can filter task list by tags.

### 📋 Requirements
- Add `tags` parameter to **GET** `/tasks`;
- `tags` parameter must be OPTIONAL!
- Ability to pass multiple tags for filtering:
  - **GET** `/tasks?tags=1,2,3`;
- Return only tasks that have the specified tags.

### 🎯 Tasks
- [ ] Update task repository logic;
- [ ] Add `tags` arguments to Task service;
- [ ] Update endpoint **GET** `/tasks` by adding `tags` parameter.
